name = "Extrae"
uuid = "8a0c07fa-ade5-4b2a-b81a-b192b2bedf88"
authors = ["Sergio Sánchez Ramírez <sergio.sanchez.ramirez@bsc.es>"]
version = "0.2.0"

[deps]
Extrae_jll = "2b2c4be0-e38c-5918-b8b4-9a308845a1e9"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"

[weakdeps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[compat]
Extrae_jll = "4.2.0"
Libdl = "1"
Preferences = "1"
julia = "1.9"

[extension]
ExtraeDistributedExt = "Distributed"
